// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://icebr.art/
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    let places = {
        "River": "Fluss",
        "Pond": "Tümpel",
        "River(Clifftop)": "Fluss (auf Hügel)",
        "Clifftop": "Hügel",
        "River(Mouth)": "Flussmündung",
        "Clifftop, Pond": "Hügel, Tümpel",
        "Sea": "Meer",
        "Pier": "Pier",
        "Sea (Rain)": "Meer (Regen)",
        "Flying": "Fliegend",
        "Flowers (Hybrid)": "Auf Blumen-Hybriden",
        "Flying(Lights)": "Fliegend (Lichter)",
        "On trees": "An Bäumen",
        "On ground": "Auf dem Boden",
        "On flowers": "Auf Blumen",
        "On white flowers": "Auf weißen Blumen",
        "Shaken tree": "Baum schütteln",
        "Underground": "Unterirdisch",
        "Ponds, River": "Tümpel, Fluss",
        "Pond, River": "Tümpel, Fluss",
        "Tree stumps": "Baumstumpf",
        "Snowballs": "Schneebälle",
        "Trees": "An Bäumen",
        "Trees (Coconut)": "Bäume (Kokosnuss)",
        "Shaken trees": "Baum schütteln",
        "Near trees": "In der Nähe von Bäumen",
        "Rotten food": "Verrottetes Essen",
        "Beach": "Strand",
        "Beach rocks": "Steinplateau am Strand",
        "Trash items": "Müll Items",
        "Villagers": "An Bewohnern",
        "Rocks(Rain)": "An Steinen im Regen",
        "Rocks(Hit)": "Stein schlagen",
        "Ground": "Auf dem Boden"
    }

    let animals = {
        "Pale Chub": "Döbel",
        "Crucian Carp": "Karausche",
        "Dace": "Hasel",
        "Carp": "Karpfen",
        "Koi": "Koi-Karpfen",
        "Goldfish": "Goldfisch",
        "Pop-eyed Goldfish": "Teleskopauge",
        "Ranchu Goldfish": "Ranchu",
        "Killifish": "Killifisch",
        "Crawfish": "Flusskrebs",
        "Soft-shelled Turtle": "Weichschildkröte",
        "Snapping Turtle": "Schnappschildkröte",
        "Tadpole": "Kaulquappe",
        "Frog": "Frosch",
        "Freshwater Goby": "Flussgrundel",
        "Loach": "Bachschmerle",
        "Catfish": "Katzenwels",
        "Giant Snakehead": "Schlangenkopf",
        "Bluegill": "Sonnenbarsch",
        "Yellow Perch": "Flussbarsch",
        "Black Bass": "Barsch",
        "Pike": "Hecht",
        "Pond Smelt": "Stint",
        "Sweetfish": "Ayu",
        "Cherry Salmon": "Masu-Lachs",
        "Char": "Saibling",
        "Golden Trout": "Goldforelle",
        "Stringfish": "Huchen",
        "Salmon": "Lachs",
        "King Salmon": "Königslachs",
        "Mitten Crab": "Wollhandkrabbe",
        "Nibble Fish": "Saugbarbe",
        "Angelfish": "Skalar",
        "Betta": "Kampffisch",
        "Neon Tetra": "Neonsalmer",
        "Rainbowfisch": "Regenbogenfisch",
        "Dorado": "Lachssalmler",
        "Gar": "Knochenhecht",
        "Saddled Bichir": "Flösselhecht",
        "Sturgeon": "Stör",
        "Sea Butterfly": "See-Engel",
        "Sea Horse": "Seepferdchen",
        "Clown Fish": "Anemonenfisch",
        "Surgeonfish": "Paletten-Doktorfisch",
        "Butterfly Fish": "Falterfisch",
        "Napoleonfish": "Napoleonfisch",
        "Zebra Turkeyfish": "Rotfeuerfisch",
        "Blowfish": "Kugelfisch",
        "Puffer Fish": "Igelfisch",
        "Anchovy": "Sardelle",
        "Horse Mackerel": "Makrele",
        "Barred Knifejaw": "Schabelbarsch",
        "Sea Bass": "Seebarsch",
        "Red Snapper": "Kaiserschnapper",
        "Dab": "Kliesche",
        "Olive Flounder": "Flunder",
        "Squid": "Kalmar",
        "Moray Eel": "Muräne",
        "Ribbon Eel": "Nasenmuräne",
        "Tuna": "Thunfisch",
        "Blue Marlin": "Marlin",
        "Giant Trevally": "Stachelmakrele",
        "Mahi-mahi": "Goldmakrele",
        "Ocean Sunfish": "Mondfisch",
        "Ray": "Rochen",
        "Saw Shark": "Sägehai",
        "Hammerhead Shark": "Hammerhai",
        "Great White Shark": "Hai",
        "Whale Shark": "Walhai",
        "Suckerfish": "Schiffshalter",
        "Football Fish": "Anglerfisch",
        "Oarfish": "Riemenfisch",
        "Barreleye": "Glaskopffisch",
        "Coelacanth": "Quastenflosser",
        "Common Butterfly": "Kohlweißling",
        "Yellow Butterfly": "Zitronenfalter",
        "Tiger Butterfly": "Schwalbenschwanz",
        "Peacock Butterfly": "Ritterfalter",
        "Common Bluebottle": "Kolibrifalter",
        "Paper Kite Butterfly": "Weiße Baumnymphe",
        "Great Purple Emperor": "Japan-Schillerfalter",
        "Monarch Butterfly": "Monarchfalter",
        "Emperor Butterfly": "Himmelsfalter",
        "Agrias Butterfly": "Agrias-Falter",
        "Raja Brooke's Birdwing": "Troides brookiana",
        "Queen Alexandra's Birdwing": "Vogelfalter",
        "Moth": "Motte",
        "Atlas Moth": "Atlasspinner",
        "Madagascan Sunset Moth": "Regenbogenfalter",
        "Long Locust": "Nasenschrecke",
        "Migratory Locust": "Wanderschrecke",
        "Rice Grasshopper": "Heuschrecke",
        "Grasshopper": "Grashüpfer",
        "Cricket": "Grille",
        "Bell Cricket": "Singgrille",
        "Mantis": "Gottesanbeterin",
        "Orchid Mantis": "Orchideenmantis",
        "Honeybee": "Honigbiene",
        "Wasp": "Wespe",
        "Brown Cicada": "Braunzikade",
        "Robust Cicada": "Hyalessa-Zikade",
        "Giant Cicada": "Riesenzikade",
        "Walker Cicada": "Bergzikade",
        "Evening Cicada": "Abendzikade",
        "Cicada Shell": "Zikadenlarvenhaut",
        "Red Dragonfly": "Feuerlibelle",
        "Darner Dragonfly": "Königslibelle",
        "Banded Dragonfly": "Quelljungfer",
        "Damselfly": "Wasserjungfer",
        "Firefly": "Leuchtkäfer",
        "Mole Cricket": "Maulwurfsgrille",
        "Pondskater": "Wasserläufer",
        "Diving Beetle": "Schwimmkäfer",
        "Giant Water Bug": "Riesenwanze",
        "Stinkbug": "Stinkwanze",
        "Man-faced Stink Bug": "Gesichtswanze",
        "Ladybug": "Marienkäfer",
        "Tiger Beetle": "Sandlaufkäfer",
        "Jewel Beetle": "Prachtkäfer",
        "Violin Beetle": "Geigenkäfer",
        "Citrus Long-horned Beetle": "Fichtenbock",
        "Rosalia Batesi Beetle": "Alpenbock",
        "Blue Weevil Beetle": "Blaurüsselkäfer",
        "Dung Beetle": "Mistkäfer",
        "Earth-boring Dung Beetle": "Gold-Mistkäfer",
        "Scarab Beetle": "Goldskarabäus",
        "Drone Beetle": "Japan-Rosenkäfer",
        "Goliath Beetle": "Goliathkäfer",
        "Saw Stag": "Sägezahn-Hirschkäfer",
        "Miyama Stag": "Hirschkäfer",
        "Giant Stag": "Riesen-Hirschkäfer",
        "Rainbow Stag": "Pracht-Hirschkäfer",
        "Cyclommatus Stag": "Cyclommatus",
        "Golden Stag": "Lamprima aurata",
        "Giraffe Stag": "Giraffenhirschkäfer",
        "Horned Dynastid": "Nashornkäfer",
        "Horned Atlas": "Atlaskäfer",
        "Horned Elephant": "Elefantenkäfer",
        "Horned Hercules": "Herkuleskäfer",
        "Walking Stick": "Stabschrecke",
        "Walking Leaf": "Blattschrecke",
        "Bagworm": "Sackträger",
        "Ant": "Ameise",
        "Hermit Crab": "Einsiedlerkrebs",
        "Wharf Roach": "Ligia exotica",
        "Fly": "Fliege",
        "Mosquito": "Moskito",
        "Flea": "Floh",
        "Snail": "Schnecke",
        "Pill bug": "Kugelasse",
        "Centipede": "Hundertfüßer",
        "Spider": "Spinne",
        "Tarantula": "Vogelspinne",
        "Scorpion": "Skorpion"
    }
    var table = document.getElementById("table_1");
    var trs = table.getElementsByTagName("tr");
    for(var i = 0; i<trs.length;i++)
    {
        var line = trs[i];
        var tds = line.getElementsByTagName("td");
        var animal = tds[2];
        var place = tds[4];
        place.innerHTML = places[place.innerHTML];
    }
})();
